### ISSUE TITLE
Font not currently 

### ISSUE THREAD

**Issue by harymk** [firatsoygul/LC75823#5]
Help needed

**Comment by harymk** [comment]
![Uploading z2{34dbf6d} (3fe49cb4-3db5-4bd8-9712-7fcc84d18558 id=0x7f0a03cd tag=BaseCommentFragment) …]()

**Comment by harymk** [comment]
![IMG_20221012_204445.jpg](https://user-images.githubusercontent.com/40994861/195382617-045f51af-3735-42c4-84e3-4758d32c7185.jpg)

**Comment by harymk** [comment]
![IMG_20221012_204451.jpg](https://user-images.githubusercontent.com/40994861/195382711-ebb83192-c43b-49e5-9973-6d302a5cd571.jpg)

**Comment by firatsoygul** [comment]
First of all, I have to say that this library includes a reverse engineering effort. I mentioned it in the first part of the Readme content. I created this library using the front panel of a tape deck. Each device has its own LCD panel. For example, your panel has symbols (dvd, vcd, mp3, title etc.) that are not in my panel. Also, while my lcd module is limited to 8 characters, your module has 10 characters. Even if the drivers of the devices are the same, lcd panels can have different segments depending on their features. The pin to which each segment is connected may also differ. Since the LCDs that are frequently used in Arduino have the same segment/pin connections regardless of the manufacturer, they can be used with the same library without modification. However, panels designed with LC75823 do not have a pin/segment connection standard. These pin connections are formed at the initiative of the engineer who designed the circuit board (However, sometimes there are panels with the same connection despite the hardware difference). These connections directly format the structure of the serial data packet sent to the drive.

Consequently, identifying this change in your hardware, you should edit the library. You should draw the connection diagram by following the connections (circuit path) between your lcd panel and the driver and the segments on the lcd. I have done this in the past using a code that turns the segment outputs of the drive on and off, respectively.

![sgm_src](https://user-images.githubusercontent.com/8572953/196022817-75ce7b96-1270-404a-9eda-ba1dd0556ba9.gif)

Meanwhile, following the serial terminal and the LCD screen, I took notes with the segment that was lit at that time.

![LC75823_Serial_Data](https://user-images.githubusercontent.com/8572953/196022897-099fd128-80d4-4872-a944-60265b4bd156.png)

Or you can do it with the help of a multimeter.

Then, using this scheme, you need to make the necessary changes in the library. In other words, by editing this library, you should create a special library for the panel you have. Roughly, you should edit the methods (symbol(), volumeChart(), sChart() etc.) that make up the SPI data packet and the variables (_container[], _symbols[], _screen[]) that carry it. LCD control, character conversion and serial packet sender, etc. other methods will continue to work as well.

You can review the version of this library that I adapted to another LCD panel [here](https://github.com/firatsoygul/PT6523).
